PRAGMA foreign_keys = ON;

-- =========================================================
-- STATIONS
-- =========================================================

INSERT INTO stations (id, name) VALUES
('ST001', 'New Delhi'),
('ST002', 'Ghaziabad'),
('ST003', 'Meerut'),
('ST004', 'Aligarh'),
('ST005', 'Kanpur'),
('ST006', 'Lucknow'),
('ST007', 'Agra'),
('ST008', 'Mathura');


-- =========================================================
-- SECTIONS
-- =========================================================

INSERT INTO sections
(id, source_station_id, target_station_id, length_km,
 track_type, electrified, max_speed)
VALUES

('SEC001', 'ST001', 'ST002', 25.0,
 'SINGLE', 1, 120),

('SEC002', 'ST002', 'ST003', 55.0,
 'SINGLE', 1, 110),

('SEC003', 'ST002', 'ST004', 95.0,
 'SINGLE', 1, 110),

('SEC004', 'ST004', 'ST005', 85.0,
 'SINGLE', 1, 120),

('SEC005', 'ST005', 'ST006', 72.0,
 'SINGLE', 1, 110),

('SEC006', 'ST001', 'ST007', 190.0,
 'SINGLE', 1, 130),

('SEC007', 'ST007', 'ST008', 55.0,
 'DOUBLE', 0, 120);


-- =========================================================
-- TRAIN SCHEDULES
-- =========================================================

INSERT INTO train_schedules
(train_id, train_name, priority, section_id,
 entry_time_min, exit_time_min,
 delay_minutes, status)
VALUES

('T001', 'Rajdhani Express', 1, 'SEC001',
 60, 90, 0, 'ON_TIME'),

('T002', 'Shatabdi Express', 1, 'SEC001',
 110, 140, 0, 'ON_TIME'),

('T003', 'Passenger 1201', 2, 'SEC001',
 155, 195, 5, 'DELAYED'),

('T004', 'Intercity Express', 1, 'SEC002',
 90, 145, 0, 'ON_TIME'),

('T005', 'Passenger 2204', 2, 'SEC002',
 160, 220, 0, 'ON_TIME'),

('T006', 'Superfast Express', 1, 'SEC003',
 120, 170, 0, 'ON_TIME'),

('T007', 'Goods Express', 2, 'SEC003',
 190, 250, 10, 'DELAYED'),

('T008', 'Superfast Express', 1, 'SEC004',
 260, 315, 0, 'ON_TIME'),

('T009', 'Lucknow Express', 1, 'SEC005',
 330, 380, 0, 'ON_TIME'),

('T010', 'Agra Intercity', 2, 'SEC006',
 80, 160, 0, 'ON_TIME'),

('T011', 'Passenger 301', 2, 'SEC007',
 200, 250, 0, 'ON_TIME');


-- =========================================================
-- MAINTENANCE REQUESTS
-- =========================================================

INSERT INTO maintenance_requests
(id, department, section_id,
 asset_id, asset_type,
 window_start_min, window_end_min,
 base_duration_min, predicted_duration_min,
 crew_size, priority, is_night)
VALUES

-- Multiple departments on SAME section.
-- These are intentionally compatible for bundling.

('M001', 'TRACK', 'SEC001',
 'TRK-001', 'TRACK',
 90, 180,
 45, NULL,
 8, 1, 0),

('M002', 'OHE', 'SEC001',
 'OHE-001', 'OHE',
 100, 190,
 30, NULL,
 5, 2, 0),

('M003', 'SIGNAL', 'SEC001',
 'SIG-001', 'SIGNAL',
 105, 200,
 25, NULL,
 4, 2, 0),


-- Another section

('M004', 'TRACK', 'SEC002',
 'TRK-002', 'TRACK',
 130, 230,
 50, NULL,
 7, 1, 0),

('M005', 'OHE', 'SEC002',
 'OHE-002', 'OHE',
 140, 240,
 35, NULL,
 5, 2, 0),


-- SEC003

('M006', 'SIGNAL', 'SEC003',
 'SIG-003', 'SIGNAL',
 160, 260,
 30, NULL,
 4, 2, 0),

('M007', 'TRACK', 'SEC003',
 'TRK-003', 'TRACK',
 170, 280,
 60, NULL,
 8, 1, 1),


-- SEC004

('M008', 'OHE', 'SEC004',
 'OHE-004', 'OHE',
 300, 390,
 40, NULL,
 5, 2, 1),


-- SEC005

('M009', 'TRACK', 'SEC005',
 'TRK-005', 'TRACK',
 350, 430,
 50, NULL,
 7, 1, 0),


-- SEC006

('M010', 'SIGNAL', 'SEC006',
 'SIG-006', 'SIGNAL',
 150, 240,
 35, NULL,
 4, 2, 0);


-- =========================================================
-- DISRUPTIONS
-- =========================================================

INSERT INTO disruptions
(id, section_id, disruption_type,
 start_time_min, end_time_min,
 delay_minutes, severity, description)
VALUES

('D001', 'SEC001', 'TRAIN_DELAY',
 110, 150,
 20, 2,
 'Rajdhani/express movement delayed due to operational issue'),

('D002', 'SEC003', 'SECTION_BLOCKED',
 220, 250,
 0, 3,
 'Temporary section blockage due to emergency inspection');


-- =========================================================
-- RESOURCE-FREE INITIAL STATE
-- =========================================================
-- Plans will be generated by the optimizer later.
-- We intentionally DO NOT insert block_plans here.